### PR TITLE
feat: Add support for uploading folders to 0gStorage

### PR DESCRIPTION
**Pull request by wanliqun**
This change is [Reviewable](https://reviewable.io/reviews/0glabs/0g-storage-client/46)

### CODE REVIEW

**Review by boqiu — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/0glabs/0g-storage-client/46)* status: 3 of 4 files reviewed, 5 unresolved discussions (waiting on @wanliqun)

___
*[`cmd/upload.go` line 138 at r1](https://reviewable.io/reviews/0glabs/0g-storage-client/46#-O5wWNjQA0wzbXBxfX7i:-O5wWNjQA0wzbXBxfX7j:bgdhf3w) ([raw file](https://github.com/0glabs/0g-storage-client/blob/db40491a9b2246d77a57928f0cfbb96ed55f7dd9/cmd/upload.go#L138)):*
> ```Go
> 
> // uploadDir handles the directory upload process by traversing the directory, batching the file uploads, and then uploading the directory metadata.
> func uploadDir(ctx context.Context, uploader *transfer.Uploader, opt transfer.UploadOption) error {
> ```

Basically, there should be few business logic in `cmd` package. Otherwise, users could not to upload a folder with such SDK.
___
*[`cmd/upload.go` line 140 at r1](https://reviewable.io/reviews/0glabs/0g-storage-client/46#-O5wTww7-qO_Sf8TwLaR:-O5wTww7-qO_Sf8TwLaS:biys9ea) ([raw file](https://github.com/0glabs/0g-storage-client/blob/db40491a9b2246d77a57928f0cfbb96ed55f7dd9/cmd/upload.go#L140)):*
> ```Go
> func uploadDir(ctx context.Context, uploader *transfer.Uploader, opt transfer.UploadOption) error {
> 	// Ensure nonce and fee options are not set for directory uploads since we might use batch.
> 	if opt.Nonce != nil || opt.Fee != nil {
> ```

For **dir** case, how about to add another command (e.g. upload-dir) to upload the entire folder. Especially output more information to users.
___
*[`cmd/upload.go` line 169 at r1](https://reviewable.io/reviews/0glabs/0g-storage-client/46#-O5wV-Ue09iiFu3Njb_l:-O5wV-Ue09iiFu3Njb_m:bm4feeq) ([raw file](https://github.com/0glabs/0g-storage-client/blob/db40491a9b2246d77a57928f0cfbb96ed55f7dd9/cmd/upload.go#L169)):*
> ```Go
> 	// Check if the directory already exists in the storage network.
> 	if found, err := uploader.FileExists(ctx, merkleTree.Root()); err == nil && found {
> 		logrus.Info("This folder already exists in the storage network")
> ```

`Warn` to report folder already exists and contents not changed.
___
*[`cmd/upload.go` line 229 at r1](https://reviewable.io/reviews/0glabs/0g-storage-client/46#-O5wWzSh6jbzjBSB0vhK:-O5wWzSh6jbzjBSB0vhL:b-9cfcws) ([raw file](https://github.com/0glabs/0g-storage-client/blob/db40491a9b2246d77a57928f0cfbb96ed55f7dd9/cmd/upload.go#L229)):*
> ```Go
> 	}
> 
> 	txHash, dataRoots, err := up.BatchUpload(ctx, datas, true, batchOpt)
> ```

1. Will some files uploaded again if batch operation failed and retry? From the user's point of view:
- If file already submitted on blockchain, then ignore the L1 submission in next retry.
- If file already uploaded on storage node, then ignore the L2 upload in next retry.
- If file partial uploaded on storage node, then continue to upload the remaining data bytes in next retry.
2. Suggest to output more information when upload folders.
___
*[`transfer/dir/fs.go` line 111 at r1](https://reviewable.io/reviews/0glabs/0g-storage-client/46#-O5wSBHCAZuVMQbNw-Yp:-O5wSBHCAZuVMQbNw-Yq:blmputf) ([raw file](https://github.com/0glabs/0g-storage-client/blob/db40491a9b2246d77a57928f0cfbb96ed55f7dd9/transfer/dir/fs.go#L111)):*
> ```Go
> //     takes the current node and its relative path as arguments. This function can perform any necessary
> //     operations, such as collecting nodes, uploading files, or logging information.
> func (node *FsNode) Traverse(actionFunc func(node *FsNode, relativePath string) error) error {
> ```

From your implementation, how about to provide a `Flatten` method for further operations?

**Review by boqiu — COMMENTED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/0glabs/0g-storage-client/46)* status: all files reviewed, 5 unresolved discussions (waiting on @wanliqun)

**Review by boqiu — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/0glabs/0g-storage-client/46)* status: all files reviewed, 6 unresolved discussions (waiting on @wanliqun)

___
*[`cmd/upload.go` line 71 at r1](https://reviewable.io/reviews/0glabs/0g-storage-client/46#-O5wYRoV0r760xjibdOr:-O5wYRoV0r760xjibdOs:bdhsyo7) ([raw file](https://github.com/0glabs/0g-storage-client/blob/db40491a9b2246d77a57928f0cfbb96ed55f7dd9/cmd/upload.go#L71)):*
> ```Go
> 
> 	uploadCmd.Flags().UintVar(&uploadArgs.expectedReplica, "expected-replica", 1, "expected number of replications to upload")
> 	uploadCmd.Flags().UintVar(&uploadArgs.maxBatchUploadFiles, "max-batch-upload-files", 16, "maximum number of files to upload per batch")
> ```

Basically, a single file submission may consume ~10 million gas. So, the default batch size should be 1.

**Review by wanliqun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/0glabs/0g-storage-client/46)* status: 0 of 5 files reviewed, 6 unresolved discussions (waiting on @boqiu)

___
*[`cmd/upload.go` line 71 at r1](https://reviewable.io/reviews/0glabs/0g-storage-client/46#-O5wYRoV0r760xjibdOr:-O60anTMERYES-jeeQxk:bmgwn78) ([raw file](https://github.com/0glabs/0g-storage-client/blob/db40491a9b2246d77a57928f0cfbb96ed55f7dd9/cmd/upload.go#L71)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Basically, a single file submission may consume ~10 million gas. So, the default batch size should be 1.
</blockquote></details>

batch not used any more
___
*[`cmd/upload.go` line 138 at r1](https://reviewable.io/reviews/0glabs/0g-storage-client/46#-O5wWNjQA0wzbXBxfX7i:-O60atbx2N6jjlsYSRH9:b9f26k3) ([raw file](https://github.com/0glabs/0g-storage-client/blob/db40491a9b2246d77a57928f0cfbb96ed55f7dd9/cmd/upload.go#L138)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Basically, there should be few business logic in `cmd` package. Otherwise, users could not to upload a folder with such SDK.
</blockquote></details>

business logic moved to `uploader` class now.
___
*[`cmd/upload.go` line 140 at r1](https://reviewable.io/reviews/0glabs/0g-storage-client/46#-O5wTww7-qO_Sf8TwLaR:-O60axbvD5751LLpMbrI:bb7f2mf) ([raw file](https://github.com/0glabs/0g-storage-client/blob/db40491a9b2246d77a57928f0cfbb96ed55f7dd9/cmd/upload.go#L140)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

For **dir** case, how about to add another command (e.g. upload-dir) to upload the entire folder. Especially output more information to users.
</blockquote></details>

done
___
*[`cmd/upload.go` line 169 at r1](https://reviewable.io/reviews/0glabs/0g-storage-client/46#-O5wV-Ue09iiFu3Njb_l:-O60az70Cypqe2WuYbl3:bb7f2mf) ([raw file](https://github.com/0glabs/0g-storage-client/blob/db40491a9b2246d77a57928f0cfbb96ed55f7dd9/cmd/upload.go#L169)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

`Warn` to report folder already exists and contents not changed.
</blockquote></details>

done
___
*[`cmd/upload.go` line 229 at r1](https://reviewable.io/reviews/0glabs/0g-storage-client/46#-O5wWzSh6jbzjBSB0vhK:-O60azkM6jhl6k3YVtUl:b-egwlan) ([raw file](https://github.com/0glabs/0g-storage-client/blob/db40491a9b2246d77a57928f0cfbb96ed55f7dd9/cmd/upload.go#L229)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

1. Will some files uploaded again if batch operation failed and retry? From the user's point of view:
- If file already submitted on blockchain, then ignore the L1 submission in next retry.
- If file already uploaded on storage node, then ignore the L2 upload in next retry.
- If file partial uploaded on storage node, then continue to upload the remaining data bytes in next retry.
2. Suggest to output more information when upload folders.
</blockquote></details>

1. the existing uploading method of `uploader` class has already handled those submission cases.
2. done
___
*[`transfer/dir/fs.go` line 111 at r1](https://reviewable.io/reviews/0glabs/0g-storage-client/46#-O5wSBHCAZuVMQbNw-Yp:-O60bAh22qhZxpR6-u2I:bb7f2mf) ([raw file](https://github.com/0glabs/0g-storage-client/blob/db40491a9b2246d77a57928f0cfbb96ed55f7dd9/transfer/dir/fs.go#L111)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

From your implementation, how about to provide a `Flatten` method for further operations?
</blockquote></details>

done

**Review by boqiu — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/0glabs/0g-storage-client/46)* status: all files reviewed, 2 unresolved discussions (waiting on @wanliqun)

___
*[`cmd/upload.go` line 58 at r2](https://reviewable.io/reviews/0glabs/0g-storage-client/46#-O6KvK5XBXj7WPYeuIST:-O6KvK5XBXj7WPYeuISU:bhyfbwq) ([raw file](https://github.com/0glabs/0g-storage-client/blob/1665a10443330d8e65b6e60f9552de59fe029f4b/cmd/upload.go#L58)):*
> ```Go
> }
> 
> func bindUploadFlags(cmd *cobra.Command, args *uploadArgument, enableNonceFee bool) {
> ```

A better way to refactor the `uploadArgs` is to extract a `TransactArgs` for L1 transaction relevant operations, including nonce, fee, and so on.

Otherwise, you could simply copy the fields of `uploadArgs` as `kv_write` did. What's more, write some `TODO` to extract common args in future.



_Code quote:_
```Go
enableNonceFee
```
___
*[`transfer/uploader.go` line 392 at r2](https://reviewable.io/reviews/0glabs/0g-storage-client/46#-O6KwpDf6Y_-Lxb76rwk:-O6KwpDf6Y_-Lxb76rwl:brjufme) ([raw file](https://github.com/0glabs/0g-storage-client/blob/1665a10443330d8e65b6e60f9552de59fe029f4b/transfer/uploader.go#L392)):*
> ```Go
> 
> 		if info != nil {
> 			txnHash = info.Tx.DataMerkleRoot
> ```

Why assign file root hash to tx hash?

**Review by wanliqun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/0glabs/0g-storage-client/46)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @boqiu)

___
*[`cmd/upload.go` line 58 at r2](https://reviewable.io/reviews/0glabs/0g-storage-client/46#-O6KvK5XBXj7WPYeuIST:-O6LM9X1BIm_KPexF7tw:bjkb15g) ([raw file](https://github.com/0glabs/0g-storage-client/blob/1665a10443330d8e65b6e60f9552de59fe029f4b/cmd/upload.go#L58)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

A better way to refactor the `uploadArgs` is to extract a `TransactArgs` for L1 transaction relevant operations, including nonce, fee, and so on.

Otherwise, you could simply copy the fields of `uploadArgs` as `kv_write` did. What's more, write some `TODO` to extract common args in future.
</blockquote></details>

extracted a `transactionArgument` struct
___
*[`transfer/uploader.go` line 392 at r2](https://reviewable.io/reviews/0glabs/0g-storage-client/46#-O6KwpDf6Y_-Lxb76rwk:-O6LMFZW9y0Ifjfos3tw:b-hfpv0l) ([raw file](https://github.com/0glabs/0g-storage-client/blob/1665a10443330d8e65b6e60f9552de59fe029f4b/transfer/uploader.go#L392)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Why assign file root hash to tx hash?
</blockquote></details>

removed

**Review by boqiu — APPROVED** [review]
> Reviewed 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/0glabs/0g-storage-client/46)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @wanliqun)

**Pull request merged**
